apiVersion: v2
name: gpu-operator
description: A Helm chart to deploy NVIDIA GPU Operator with custom Cilium Network Policies.
version: 1.0.0
appVersion: 25.3.4
home: https://github.com/giantswarm/gpu-operator-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  application.giantswarm.io/team: tenet
dependencies:
- name: gpu-operator
  repository: https://helm.ngc.nvidia.com/nvidia
  version: 25.3.4
