apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-{{ include "gpu-operator.fullname" . }}-talk-to-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: "gpu-operator"
    {{- include "gpu-operator.labels" . | nindent 4 }}
spec:
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      - port: "6443"
        protocol: TCP
      - port: "8081"
        protocol: TCP
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gpu-operator.name" . }}
  ingress:
  - fromEntities:
    - cluster
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      - port: "6443"
        protocol: TCP
      - port: "8000"
        protocol: TCP
      - port: "8081"
        protocol: TCP
